macro(check_for_cpp17_support ARGV1)
	if( (CMAKE_CXX_COMPILER_ID MATCHES "MSVC"       AND CMAKE_CXX_COMPILER_VERSION VERSION_GREATER_EQUAL "19.15") OR
		(CMAKE_CXX_COMPILER_ID MATCHES "GNU"        AND CMAKE_CXX_COMPILER_VERSION VERSION_GREATER_EQUAL "8") OR
		(CMAKE_CXX_COMPILER_ID MATCHES "Clang"      AND CMAKE_CXX_COMPILER_VERSION VERSION_GREATER_EQUAL "8") OR
		(CMAKE_CXX_COMPILER_ID MATCHES "AppleClang" AND CMAKE_CXX_COMPILER_VERSION VERSION_GREATER_EQUAL "11"))
	  set(${ARGV1} 1)
	endif()		
endmacro()

macro(check_for_cpp20_support ARGV1)
	if( (CMAKE_CXX_COMPILER_ID MATCHES "MSVC"       AND CMAKE_CXX_COMPILER_VERSION VERSION_GREATER_EQUAL "19.30") OR
		(CMAKE_CXX_COMPILER_ID MATCHES "GNU"        AND CMAKE_CXX_COMPILER_VERSION VERSION_GREATER_EQUAL "12") OR
		(CMAKE_CXX_COMPILER_ID MATCHES "Clang"      AND CMAKE_CXX_COMPILER_VERSION VERSION_GREATER_EQUAL "13") OR
		(CMAKE_CXX_COMPILER_ID MATCHES "AppleClang" AND CMAKE_CXX_COMPILER_VERSION VERSION_GREATER_EQUAL "13"))
	  set(${ARGV1} 1)
	endif()
endmacro()