name: Build
on: push

jobs:

  Linux:
    runs-on: ubuntu-22.04
    strategy:
      matrix:
        compiler: [g++, clang]
        build_type: [Debug, Release]
        include:
          - compiler: g++
            c_compiler: gcc-12
            cpp_compiler: g++-12
          - compiler: clang
            c_compiler: clang-12
            cpp_compiler: clang++-12
          - build_type: Debug
            output_name_postfix: _d
            
    env:
      CC: ${{matrix.c_compiler}}
      CXX: ${{matrix.cpp_compiler}}
      
    steps:
      - uses: actions/checkout@v3
        with:
          submodules: recursive
      - name: Install packages
        run: |
          wget -O - https://apt.llvm.org/llvm-snapshot.gpg.key 2>/dev/null | sudo apt-key add -
          sudo add-apt-repository 'deb http://apt.llvm.org/focal llvm-toolchain-focal-12 main' -y
          sudo add-apt-repository ppa:ubuntu-toolchain-r/test
          sudo apt update
          sudo apt install build-essential gcc-12 g++-12 clang-12 lcov valgrind
          sudo update-alternatives --install /usr/bin/gcc gcc /usr/bin/gcc-12 90
          sudo update-alternatives --install /usr/bin/g++ g++ /usr/bin/g++-12 90
          sudo update-alternatives --install /usr/bin/gcov gcov /usr/bin/gcov-12 90  
          sudo update-alternatives --install /usr/bin/clang clang /usr/bin/clang-12 90
          sudo update-alternatives --install /usr/bin/clang++ clang++ /usr/bin/clang++-12 90
          
      - name: Check versions
        run: |
          cmake --version
          ${{matrix.c_compiler}} --version
          ${{matrix.cpp_compiler}} --version
          gcov --version
          python --version
      - name: Build
        run: |
          mkdir build
          cd build
          cmake -DCPPLI_ENABLE_COVERAGE=ON -DCMAKE_BUILD_TYPE=${{matrix.build_type}} ..
          cmake --build . --config ${{matrix.build_type}}
      - name: Test
        run: |
          cd bin
          valgrind --leak-check=full --track-origins=yes --error-exitcode=1 ./cppli_tests${{matrix.output_name_postfix}}
      - uses: codecov/codecov-action@v3
        if: ${{ matrix.compiler == 'g++' && matrix.build_type == 'Debug' }}
        with:
          gcov: true